--- #YAML:1.0
name:                Devel-StackBlech
version:             0.04
abstract:            Dumps your stack, all of it, somewhere
license:             ~
author:              
    - Joshua ben Jore <jjore@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Sub::Exporter:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
